name: Docker Image CI

on:
  push:
    branches: [ master ]
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pulzar
        
    steps:
    - uses: actions/checkout@v2
    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pulzar-ui
    - name: Tags
      run: |
        docker tag pulzar-ui ${{ secrets.DOCKER_USER }}/pulzar-ui:${{ github.sha }}
        docker tag pulzar-ui ${{ secrets.DOCKER_USER }}/pulzar-ui:latest
    - name: Push image
      run: |
        docker push ${{ secrets.DOCKER_USER }}/pulzar-ui:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/pulzar-ui:latest
